### PR TITLE
Upgrade to Qt Creator 4.9

### PR DESCRIPTION
**Pull request by iohanaan**

### CODE REVIEW

**Comment by iohanaan** [comment]
Address issue #335

**Comment by gavanderhoorn** [comment]
I'm always amazed by the nr of (breaking) changes the Qt (Creator) devs introduce in new minor versions.

It's obviously positive that they keep working on their product, but it makes the life of plugin maintainers so much harder.

**Comment by Levi-Armstrong** [comment]
@iohanaan Thank you for your contribution. I should be able to pull it down this week and test it and provide feedback if necessary.

**Comment by vincent-hui** [comment]
@Levi-Armstrong will you submit ROS plugin to the Qt Creator source on codereview.qt-project.org ? You can save time consuming effort to adapt it to API changes.
https://github.com/ros-industrial/ros_qtc_plugin/issues/325

**Comment by Levi-Armstrong** [comment]
> @Levi-Armstrong will you submit ROS plugin to the Qt Creator source on codereview.qt-project.org ? You can save time consuming effort to adapt it to API changes.

I agree it would be nice, but the code is not to a state that would be acceptable. It does not conform the there style guide and it is not cross platform. It would require more effort than I have at the moment to get the code up to standard where I would feel comfortable submitting. This does not prevent other though from submitting it and addressing all request changes to get it merged.

**Comment by Levi-Armstrong** [comment]
merged in #342

**Pull request closed without merging**
