### PR TITLE
port to Qt Creator 4.11

### PR DESCRIPTION
**Pull request by christian-rauch**
PR with the "4.11" commit subset of https://github.com/ros-industrial/ros_qtc_plugin/pull/417

@v4hn Can you rebase your PR https://github.com/christian-rauch/ros_qtc_plugin/pull/1 on this and report any regressions since 4.9.2?

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
@christian-rauch Do you want to wait on @v4hn review before merging?

**Comment by christian-rauch** [comment]
> @christian-rauch Do you want to wait on @v4hn review before merging?

Yes. I gave it a quick shot and the usual set of features that I use work. But if there are more issues, it's better to solve them now with the smaller set of commits.

**Comment by Levi-Armstrong** [comment]
Sounds good. Ping me when ready. @christian-rauch Would you be interested in being added as a maintainer?

**Comment by christian-rauch** [comment]
> Would you be interested in being added as a maintainer?

Would that mean I can accept PR and publish updated upstream? I will probably provide updated PRs for the plugin if I have time and want to use a newer Qt Creator version.

**Comment by Levi-Armstrong** [comment]
> Would that mean I can accept PR and publish updated upstream? I will probably provide updated PRs for the plugin if I have time and want to use a newer Qt Creator version.

All of the above. 

I plan on create a snapcraft release once 4.14 is merged which should not take to long to do.

**Comment by christian-rauch** [comment]
@Levi-Armstrong This can be merged now and a new 4.12 branch based on this can be created.

I am happy to become one of the maintainers.

**Comment by Levi-Armstrong** [comment]
@christian-rauch The new branch is created and I have given you write access.

**Pull request merged**
