### PR TITLE
Remove useo of -i argument when creating bash

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Creating an interactive bash terminal as a child process was cause weird cpu spikes and crashes. This was originaly introduced to load environment variable added to the .bashrc. I have since found out that it is better to add environment variable to the .profile over the .bashrc so application like QtCreator get these since they are considered system level environment variables. I will add this to the wiki.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Do you see any issues with asking developers to add environment variables that normally get added to the .bashrc to .profile so application get these environment variables?

**Comment by gavanderhoorn** [comment]
I'm not sure.

I seem to remember differences in signal handling between interactive and non-interactive `bash` sessions and child processes, but would have to look that up.

Which environment variables are you referring to here, specifically? Having people edit their `.profile` is going to be an additional step, so from a UX pov not so nice. The file may also not always exist, so that could potentially confuse users.

For building a Catkin workspace with `catkin_tools` you don't need to `source` anything, if you use the `catkin config --extend ..` option. `catkin build` would then also not need to be run from a shell that has `source`d anything.

I also don't believe `catkin_init_workspace` is needed. Do you have any particular reason to include it?

Finally: would using [`QProcessEnvironment::systemEnvironment()`](https://doc.qt.io/qt-5/qprocessenvironment.html#systemEnvironment) to explicitly setup the env of the process you create not be an option? Or using something like `bash -c 'source /opt/ros/whatever/..; the_actual_cmd_to_run' be an option?

**Comment by Levi-Armstrong** [comment]
The only case I have ran is with cuda and GUROBI require certain environment variables to be set. I believe if you added this to your .profile you would not add them to the .bashrc file. I believe that items in your .profile file get considered as system environment variables. I did try just sourcing the .bashrc as you suggested but the .bashrc check at the beginning if it is an interactive bash and if not it exits. If the user created its own then this would not be the case.

```
export PATH=/usr/local/cuda-9.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
export GUROBI_HOME=/opt/gurobobi810/linux64
```

**Comment by gavanderhoorn** [comment]
> The only case I have ran into is with cuda and GUROBI require certain environment variables to be set. 

I've seen applications / IDEs that allow to run cmdline applications (ie: compilers, linkers, other progs) offer specific *environment setup* screens/functionality for that.

They import the user's environment (as in: take whatever is part of the environment when the application was started) and then show some sort of key-value table where users can configure additional env vars to be passed on to the invoked programs.

That would seem to be much more transparent and reproducable (ie: completely clear what is part of the environment and not dependent on whatever a user has added to a out-of-process file somewhere). It would also allow to configure different environments for different workspaces (fi: different versions of CUDA for different workspaces without Qt Creator restarts and editing files in between).

> I did try just sourcing the .bashrc as you suggested but the .bashrc check at the beginning if it is an interactive bash and if not it exits.

I'm not sure I understand completely.

**Comment by Levi-Armstrong** [comment]
Qt creator does provide this functionality but I have made it read only because of sourcing ros setup.bash, but I think I should be able to enable edit and see if this causes any issues. I think I can get it to work.

> I'm not sure I understand completely.

Internally I start bash process for executing some ROS command and if I just run `bash -c` from a QProcess it is not a interactive bash process and the .bashrc will not get sourced because it is only run if the bash process is an interactive bash.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Thank you for the recommendation. Now you can edit the environment variable in the build configuration and the persist.

**Pull request merged**
