### PR TITLE
Fix several issues (Update Environment, WS Initialization, and Run Config Package List)

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@Jmeyer1292 Can you please review?

**Comment by Levi-Armstrong** [comment]
@Jmeyer1292 Friendly ping. :)

**Comment by Jmeyer1292** [comment]
+1

**Comment by passgall** [comment]
I followed your suggestion and it does work. Very thanks!

**Comment by passgall** [comment]
hi,
I have found another question. When I run node in qtcreator. It shows this message in QT Ros terminals "run talker" where the talker is node name. But the package name "beginner_tutorials" is lost. So there are no other message shown in the QT Ros terminal.
When I used "rosrun beginner_tutorials talker" in ubuntu terminal. It works very well.So there are some errors in the /ros_qtc_plugin.Can you give me sugesstions?

**Comment by Levi-Armstrong** [comment]
So have you done a recent update; I thought this PR fixed the issue you are having?

**Pull request merged**
