### PR TITLE
Update How-to-Install-Users.rst

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Update the install procedure in the sphinx documentation to address issue #438

### CODE REVIEW

**Comment by christian-rauch** [comment]
Alright. So you are dropping the custom binary installers? Are you planning to bring them back eventually with updated Qt Creator?

While the approach with the CI publishing the plugin archive streamlines the installation quite a bit, my fear is that people will nonetheless update their Qt Creator and break the compatibility with the plugin before we manage to update the API in the plugin. The instructions that I initially created will download the most recent plugin release. At the moment, I am updating the plugin to stay compatible with the latest Qt Creator release. But there is no guarantee that the latest plugin release will be compatible with the latest Qt Creator release.

Maybe we should fix the Qt Creator and plugin versions in the user installation guide with links to the official offline Qt Creator installer for a fixed version and a link to a compatible plugin archive version. This would make sure that those users do not break their setup accidentally, since they cannot update automatically to an incompatible version. We could then update the instructions from time to time with new links to more recent compatible Qt Creator and plugin releases.

... or we write a bash script that handles this by installing a fixed Qt Creator version and compatbile plugin archive,

**Comment by Levi-Armstrong** [comment]
> Alright. So you are dropping the custom binary installers? Are you planning to bring them back eventually with updated Qt Creator?

I was planning to drop the custom binary installer for now. I tried to revive it but things have changed on the Qt Creator side which will take a while to figure out.

> While the approach with the CI publishing the plugin archive streamlines the installation quite a bit, my fear is that people will nonetheless update their Qt Creator and break the compatibility with the plugin before we manage to update the API in the plugin. The instructions that I initially created will download the most recent plugin release. At the moment, I am updating the plugin to stay compatible with the latest Qt Creator release. But there is no guarantee that the latest plugin release will be compatible with the latest Qt Creator release.

>  Maybe we should fix the Qt Creator and plugin versions in the user installation guide with links to the official offline Qt Creator installer for a fixed version and a link to a compatible plugin archive version. This would make sure that those users do not break their setup accidentally, since they cannot update automatically to an incompatible version. We could then update the instructions from time to time with new links to more recent compatible Qt Creator and plugin releases.

I think adding a table with links to the Qt Creator version along with the ROS Plugin would be good to help prevent installing the wrong version. 

> ... or we write a bash script that handles this by installing a fixed Qt Creator version and compatbile plugin archive,

This also sounds good.

I also want to see if there is a way to take an existing installer and expand it with additional options. Were we could pull the Qt Creator Installer and then introduce our plugin to it to avoid having to build the full installer but I have not looked into this yet.

**Comment by christian-rauch** [comment]
> I think adding a table with links to the Qt Creator version along with the ROS Plugin would be good to help prevent installing the wrong version.

I like this idea of a table with compatible versions and links to the installers and archives. Can you already add this table now for Qt Creator 5.0 and the plugin 0.4?

**Comment by Levi-Armstrong** [comment]
> > I think adding a table with links to the Qt Creator version along with the ROS Plugin would be good to help prevent installing the wrong version.
> 
> I like this idea of a table with compatible versions and links to the installers and archives. Can you already add this table now for Qt Creator 5.0 and the plugin 0.4?

Yea, I will add the table to this and the readme.

**Comment by christian-rauch** [comment]
Is this still relevant? I documented the binary installation process at https://github.com/ros-industrial/ros_qtc_plugin for users and the build instructions for developers. I guess this would affect https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html. Should we just merge this now? The binary offline installers are still available but I don't think anyone can support them and we should point people to the "new" binary distribution.

**Review by christian-rauch — APPROVED** [review]

**Pull request merged**
