### PR TITLE
Setup Script

### PR DESCRIPTION
**Pull request by oxoocoffee**
I updated and tested setup script on clean vbox installed ubuntu.
Script check for missing dependency packages and installs them as needed.
Also after setup.sh script is finished there is setup.log generated each run. 
This log file is removed on each run so we have clean log. This way users can submit full build logs to bugs
Also each step has duration timestamp.

I was also thinking about checking and adding additional check and setup found on your WIKI. So it is automated. What do you think. I tested this script few times if you find any issues or suggestions please le me know

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Great Job! I am Ok with adding additional checks. Do you want to do this as part of this PR or should I merge this once the conflicts are resolved?

**Comment by Levi-Armstrong** [comment]
OK, Can you rebase this on the latest; I am unable to merge it as is?

**Comment by Levi-Armstrong** [comment]
@oxoocoffee I believe you mention that you are currently busy with a project, would you like me too rebase this so it may be merged?

**Comment by oxoocoffee** [comment]
Sorry for delay. Please do.

**Comment by oxoocoffee** [comment]
Hello Levi. I am back to help little more. Are you on IM of some kind?

**Comment by Levi-Armstrong** [comment]
This is ready to merge once it gets rebased.

**Comment by Levi-Armstrong** [comment]
If you are interested there have been request on upgrading to 4.3 to take advantage of the cmake server_mode. #126 This should eliminate the need to run the code block generator but not sure how much work is involved in upgrading. Also even if it is an option seeing we build with catkin tool and catkin_make which under the hood call cmake but my cause limitation during implementation of using the server mode for building the code model.

**Comment by oxoocoffee** [comment]
We should be good to go now

**Comment by Levi-Armstrong** [comment]
Great! Thank you. I am, we currently use slack. I could create a channel for discussing this plug-in if you would like?

**Comment by oxoocoffee** [comment]
Please do...

**Pull request merged**
