### PR TITLE
clang format

### PR DESCRIPTION
**Pull request by christian-rauch**
This adapts the code style to the one used by Qt Creator using clang-format with the style file from the upstream project: https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/.clang-format.

Since this PR touches every file, I would hold off the merge until we know that this style file is the correct one that we need to get the plugin merged upstream.

Edit: I added a script that applies the style to all source and header files. It has to be called from the source root. Note that different clang-format versions can result in different results. This is with clang-format 10.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
The other piece is the variable/parameter naming. Half way through writing this plugin I was using the ROS naming convention and then thought about the possible of contributing back. Is there a way to easily go through and change variable and parameter names?

**Comment by christian-rauch** [comment]
> The other piece is the variable/parameter naming.

Is this the `m_` convention for member variables? This can be done with the refactoring function in Qt Creator.

**Comment by Levi-Armstrong** [comment]
> > The other piece is the variable/parameter naming.
> 
> Is this the `m_` convention for member variables? This can be done with the refactoring function in Qt Creator.

Yea, I also did not know if clang-tidy would do some of this instead of manually having to go through.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by christian-rauch** [comment]
> > > The other piece is the variable/parameter naming.
> > 
> > 
> > Is this the `m_` convention for member variables? This can be done with the refactoring function in Qt Creator.
> 
> Yea, I also did not know if clang-tidy would do some of this instead of manually having to go through.

clang-tidy can check and change variable name conventions: https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html#cmdoption-arg-memberprefix but I haven't found a `.clang-tidy` in the upstream project. I will look into this.

**Comment by vincent-hui** [comment]
If ros_qtc_plugin is added to the super-repo of Qt Creator as submodule, there would be no hard requirement to stick to Qt Creator coding style rules.

**Comment by christian-rauch** [comment]
Since integrating this into the Qt Creator upstream repo is not on the horizon, there is no real need to apply their code style. I am going to close this as the applied code style will clash anyway with the current state. The `.clang-format` file from this PR can still be reused later.

**Pull request closed without merging**
