### PR TITLE
build plugin and archive via CMake

### LINKED ISSUE #422: provide a standalone plugin archieve
Qt Creator supports installing plugins from an archive:
qtc_plugin_archive

I couldn't find documentation on how this archive is structured, but I think it is simply a zipped version of all the files that get installed after the build step.

Would it be possible to provide this as a build artefact on GitHub? This would allow using the binary distribution of Qt Creator (https://www.qt.io/offline-installers).

### PR DESCRIPTION
**Pull request by christian-rauch**
This adds a CMake build script to build the plugin and create a plugin archive.

It turns out, you do not have to compile Qt Creator from scratch if you install the "Plugin Development" package via the official binary installer. This is equivalent to installing the header and libraries (a.k.a. SDK) from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtcreator/qt.tools.qtcreatordev/.

I updated the build instructions accordingly. Using the distributed binary SDK and creating the archive makes building this much easier. I think we should add this to the CI at some point, so that the plugin archives are published on GitHub.

~~I am marking this as WIP for now, since I still have to figure out which additional resources (like icons, templates) have to be installed. Currently, the archive only includes the .so file.~~

Fixes #422 .

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
I will be able to take a look next week and test the process.

**Comment by christian-rauch** [comment]
I added the shared files (templates, ...) to the archive. The archive now has the file structure:
```
.
├── lib
│   └── qtcreator
│       └── plugins
│           └── libROSProjectManager.so
└── share
    └── qtcreator
        ├── generic-highlighter
        ├── styles
        └── templates
            └── wizards
```
which would match the root file structure of the Qt Creator installation.

However, the Qt Creator plugin import GUI will extract the archive to where `IDE_PLUGIN_PATH` would point (`~/Qt/Tools/QtCreator/lib/qtcreator/plugins` with the default binary distribution). This will place all the shared files (templates, ...) within the library path and Qt Creator will not be able to find the templates afterwards.

The correct path would be `IDE_OUTPUT_PATH` (`~/Qt/Tools/QtCreator/`). You can work around this issue by manually extracting the archive to this directory.

@Levi-Armstrong I removed all the qmake project files. I assume we won't need these if you are satisfied with the CMake build script. CMake seems to be the default now for building Qt Creator plugins (at least the plugin template uses CMake now) and using the binary Qt Creator distribution makes building and maintaining the plugin much easier.

Output plugin archive: [ROSProjectManager-0.3.11-Linux-x86_64.tar.gz](https://github.com/ros-industrial/ros_qtc_plugin/files/7072771/ROSProjectManager-0.3.11-Linux-x86_64.tar.gz)

**Comment by Levi-Armstrong** [comment]
Sure. If they have moved to using CMake that is fine with me.

**Comment by christian-rauch** [comment]
With the new CMake instructions, I also replaced the old `setup.sh` script, that downloaded the Qt Creator source and compiled everything, with a new `setup.py` that directly downloads the binaries for Qt Creator, the Plugin Development and Qt. This sript can then also be used in a CI environment.

@Levi-Armstrong @vincent-hui Could you give the CMake script a try by following the build instructions in the `README.md`? In a new environment, this boils down to:
```
./setup.py
cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/tmp/qtc_sdk/Tools/QtCreator;/tmp/qtc_sdk/5.15.0/gcc_64"
cmake --build build --target package
```
and then extracting the archive (`ROSProjectManager-0.3.11-Linux-x86_64.zip`) to your Qt Creator installation (e.g. `~/Qt/Tools/QtCreator/`).

If this works for you and you are happy with these simplified instructions, I am going to merge this.

**Comment by christian-rauch** [comment]
This is now used in the CI pipeline #435 to test the build and create plugin archives for releases. Together with the setup script, I am quite confident that the plugin can be build reliably this way on other setups.

@Levi-Armstrong Can you have a look at this "cmake" and the other "ci" PR? Can you leave a comment if I can go on merging this into `devel`?

**Comment by Levi-Armstrong** [comment]
I used the setup.py to build without any issues and I am now downloading 5.15 to test importing the plugin.

**Comment by Levi-Armstrong** [comment]
Everything was imported and worked as expected. I did not test everything but was able to build the workspace.

**Review by Levi-Armstrong — APPROVED** [review]
It would be good after this is merged to update the sphinx documentation with the new install instructions.

**Comment by christian-rauch** [comment]
> It would be good after this is merged to update the sphinx documentation with the new install instructions.

I updated the developer instructions with the information in the `README.md` and update the gdb instructions a bit.

Edit:
I did not test if the new doc actually compiles since `sphinx-versioning` gives me some python error.

**Comment by Levi-Armstrong** [comment]
Ok, I will work out any issues after this is merged.

**Pull request merged**
