### PR TITLE
update installation instructions for snap package

### PR DESCRIPTION
**Pull request by christian-rauch**
I created a snap package that includes Qt Creator and the plugin as a replacement for the old binary installer: https://snapcraft.io/qtcreator-ros. This runs as a "classic" snap with full access to the host system and should therefore behave like a regular Qt Creator installation.

This PR is adding the installation instructions to the main page.

@Levi-Armstrong I am currently hosting the instructions for building the snap in a [separate repository](https://github.com/christianrauch/qtcreator-ros-snap). Do you want to create a dedicated repo inside `ros-industrial` (e.g. https://github.com/ros-industrial/qtcreator-ros-snap) where we can maintain the instructions and update once a new Qt Creator and ROS plugin version have been released? Additionally, I can make you a contributor on the http://snapcraft.io page so that you can release new snap packages without me.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Is there a reason not host it in this repository? I currently do this in another [repo](https://github.com/tesseract-robotics/tesseract_ignition) which seems to work there.

**Comment by christian-rauch** [comment]
If the `snapcraft.yaml` is in the repo and the repo is connected to the snapcraft.io build server, then the build server will release a new version to the `edge` channel every time there is a new commit in the repo on the HEAD branch (`devel` in our case). Right now, the `snapcraft.yaml` has fixed versions for the Qt Creator and the plugins, so this will re-release the very same versions multiple times to the `edge` channel, until the `snapcraft.yaml` is updated with new versions after a release.

If we put the `snapcraft.yaml` in a separate repo, we only have to commit once we update the versions and then the `edge` channel will only get new updated once we test a new version.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
@christian-rauch How public do you want the repo to be? We could put it in the release org [here](https://github.com/ros-industrial-release), but if you think it needs more visibility we could put it under this org.

**Comment by christian-rauch** [comment]
The repo could be anywhere as long as a couple of `ros_qtc_plugin` maintainers have access to update the `snapcraft.yaml` after and Qt Creator or plugin update.

**Comment by Levi-Armstrong** [comment]
@marip8 Are you able to create release repository in the ros-industrial-release organization for this repo and give @christian-rauch and myself maintainership?

**Comment by marip8** [comment]
I currently don't have access to add a repo. I'll look into it, but maybe @gavanderhoorn can do this in the short term

**Comment by christian-rauch** [comment]
I am going to merge the snap installation instructions now. Let me know when there is a common repo where I can push the snap package. I will then also add you as maintainer/collaborator on snapcraft.io so you can release new versions without me.

**Pull request merged**
