### PR TITLE
Fix Qt5.9

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@oxoocoffee Would have time to review this PR?

**Comment by xlan09** [comment]
Thanks for fixing this, @Levi-Armstrong  
Is it ok to update & upgrade now? I run `sudo apt-get update && sudo apt-get install qt57creator-plugin-ros`, still getting `libqbscore.so.1.7: cannot open shared object file: No such file or directory`. I just upgraded to 16.04, with qt5.9.1.

**Comment by Levi-Armstrong** [comment]
I am currently working through the Debian release, which is painful to say the least. I am able to get it to build without the ClangCodeModel, just working through dependency so the ClangCodeModel is available. Maybe available sometime today.

**Comment by xlan09** [comment]
ok, thanks, no rush. I just want to make sure I did the right thing to update it. Like you mentioned, it's actually working without any problem, though it has that missing lib popup.

**Pull request merged**
